name: 'Setup'
inputs:
  python-version:  # id of input
    description: 'Python version'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: false
        python-version: ${{ inputs.python-version }}
        # activate-environment: true
    - name: Install Requirements
      shell: bash
      #TODO: re-test with input python version
      run: |
        uv python install 3.12
        uv venv --relocatable --python 3.12
        uv pip install build123d
