name: 'Setup'
inputs:
  python-version:
    description: 'Python version'
    required: true

env:
  UV_INSTALL_DIR: "${GITHUB_WORKSPACE}/uv"

runs:
  using: "composite"
  steps:
    - name: Install uv into local working directory
      shell: bash
      run: |
        mkdir uv
        curl -LsSf https://astral.sh/uv/install.sh | env UV_UNMANAGED_INSTALL="${GITHUB_WORKSPACE}/uv" sh
        export PATH="${GITHUB_WORKSPACE}/uv:$PATH"
        chmod +x ${GITHUB_WORKSPACE}/uv/uv
        uv --version
        
    - name: Fetch Standalone Python
      shell: bash
      run: |
        mkdir python
        mkdir pyinst
        export UV_PYTHON_BIN_DIR="`pwd`/python"
        export UV_PYTHON_INSTALL_DIR="`pwd`/pyinst"
        export PATH="${GITHUB_WORKSPACE}/uv:$PATH"
        # Fetch the exact version
        uv python install 3.12.12
