import os
import sys
import subprocess
import pytest
from pathlib import Path

# The workflow will pass the path to the extracted portable executable
PORTABLE_PYTHON = os.environ.get("PORTABLE_PYTHON_EXE")


@pytest.fixture(autouse=True)
def check_env():
    """Ensure the environment variable is set and the executable exists."""
    if not PORTABLE_PYTHON or not Path(PORTABLE_PYTHON).exists():
        pytest.fail(f"Portable Python not found at {PORTABLE_PYTHON}")


def run_portable(cmd_args, **kwargs):
    """Helper to run commands within the isolated portable environment."""
    result = subprocess.run(
        [PORTABLE_PYTHON] + cmd_args, capture_output=True, text=True, **kwargs
    )

    # Force pytest to display the actual tracebacks on failure
    if result.returncode != 0:
        print(f"\n--- COMMAND FAILED (Exit Code {result.returncode}) ---")
        print(f"STDOUT:\n{result.stdout}")
        print(f"STDERR:\n{result.stderr}")
        result.check_returncode()

    return result


def test_cli_json_schema_root():
    """Test standard build123d_cli schema generation for command groups."""
    result = run_portable(["-m", "build123d_cli", "--json-schema"])
    assert result.returncode == 0
    assert '"py_gearworks"' in result.stdout
    assert '"bd_warehouse"' in result.stdout


def test_cli_json_schema_packages():
    """Test standard schema generation for specific package command groups."""
    result_pgw = run_portable(["-m", "build123d_cli", "py_gearworks", "--json-schema"])
    assert result_pgw.returncode == 0
    assert '"SpurGear"' in result_pgw.stdout

    result_bdw = run_portable(["-m", "build123d_cli", "bd_warehouse", "--json-schema"])
    assert result_bdw.returncode == 0


def test_e2e_cli_export(tmp_path):
    """Test the CLI using fire's syntax to instantiate a gear and call the monkeypatched export_directory method."""
    out_dir = tmp_path / "cli_out"
    out_dir.mkdir()

    # fire CLI syntax: <group> <class> --kwarg=val <method_to_call> <method_arg>
    result = run_portable(
        [
            "-m",
            "build123d_cli",
            "py_gearworks",
            "SpurGear",
            "--module=1",
            "--teeth=10",
            "--thickness=5",
            "-",  # fire separator for "global command"
            "export_directory",
            str(out_dir),
        ]
    )
    assert result.returncode == 0

    # The monkeypatch generates build123d_YYYY-MM-DD_HH_MM_SS.stl and .svg
    files = list(out_dir.glob("*"))
    assert any(f.suffix == ".stl" for f in files), "STL file was not generated by CLI"
    assert any(f.suffix == ".svg" for f in files), "SVG file was not generated by CLI"


def test_e2e_script_export(tmp_path):
    """Test end-to-end model generation directly via an imported Python script."""
    script_path = tmp_path / "generate_gear.py"
    out_dir = tmp_path / "script_out"
    out_dir.mkdir()

    # We import build123d_cli just to activate the export_directory monkeypatch
    code = f"""
import build123d_cli
from py_gearworks import SpurGear

gear = SpurGear(module=1, teeth=10, thickness=5)
gear.export_directory('{out_dir.as_posix()}')
"""
    script_path.write_text(code)
    run_portable([str(script_path)])

    files = list(out_dir.glob("*"))
    assert any(
        f.suffix == ".stl" for f in files
    ), "STL file was not generated by Script"


def test_pip_install_isolation():
    """Ensure EXTERNALLY-MANAGED is removed so pip works, but without polluting the host."""
    result_install = run_portable(["-m", "pip", "install", "six"])
    assert result_install.returncode == 0

    # Verify the package successfully imports inside the portable env
    result_import = run_portable(
        ["-c", "import six; print('SUCCESS: ' + six.__name__)"]
    )
    assert "SUCCESS: six" in result_import.stdout


def test_path_isolation():
    """Ensure sys.path doesn't bleed out and pick up host runner/system packages."""
    result = run_portable(["-c", "import sys; print('\\n'.join(sys.path))"])
    paths = result.stdout.lower()

    # Verify GitHub Actions runner paths do not leak into the portable environment
    assert (
        "hostedtoolcache" not in paths
    ), "Leak detected: Runner tool cache in sys.path"
    assert (
        "appdata\\local\\programs\\python" not in paths
    ), "Leak detected: Global Windows AppData in sys.path"
    assert "run/user" not in paths, "Leak detected: Global Linux user paths in sys.path"
